/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Administrators: typeof import('./src/components/administrators.vue')['default']
    ApiExplorer: typeof import('./src/components/api-explorer.vue')['default']
    Bounces: typeof import('./src/components/bounces.vue')['default']
    ComboTable: typeof import('./src/components/shared/combo-table.vue')['default']
    Configurations: typeof import('./src/components/configurations.vue')['default']
    Editor: typeof import('./src/components/shared/editor.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    Notifications: typeof import('./src/components/notifications.vue')['default']
    OidcCallback: typeof import('./src/components/oidc-callback.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subscriptions: typeof import('./src/components/subscriptions.vue')['default']
    Viewer: typeof import('./src/components/shared/viewer.vue')['default']
  }
}
