apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "NotifyBC.fullname" .}}
data:
  {{- range $key, $val := .Values.configMap }}
  {{- $key | nindent 2 }}: |
    {{- tpl $val $ | nindent 4 }}
  {{- end }}
