apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "NotifyBC.fullname" .}}
data:
  config.local.js: |
    module.exports = {
      internalHttpHost: 'http://{{include "NotifyBC.fullname" .}}:{{ .Values.service.port }}',
      inboundSmtpServer: {
        listeningSmtpPort: 2525,
        options: {
          secure: true
        }
      }
    }
  middleware.local.js: |
    module.exports = {
      apiOnly: {
        morgan: {
          enabled: false,
        },
      },
    };
  db.datasource.local.js: |
    module.exports = {
      name: 'db',
      connector: 'mongodb',
      hostname: process.env.DATABASE_SERVICE_NAME,
      port: process.env.DB_PORT || 27017,
      user: process.env.MONGODB_USER,
      password: process.env.MONGODB_PASSWORD,
      database: process.env.MONGODB_DATABASE,
    };
