apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "NotifyBC.fullname" . }}-allow-db-ingress
  labels:
    {{- include "NotifyBC.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    - ports:
        - protocol: TCP
          port: 27017
  policyTypes:
    - Ingress
