ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    # todo: avoid hard-coding
    - host: 20.48.142.98.nip.io
      paths:
        - path: /
  tls:
    - secretName: tls-secret
      hosts:
        - 20.48.142.98.nip.io
