environment: prod

image:
  repository: ghcr.io/bcgov/des-notify-bc
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 'latest'
fluentbit:
  persistence:
    # Overrides netapp-file-backup which is only valid in OpenShift.
    storageClassName: hostpath
cronJob:
  # Overrides netapp-file-backup which is only valid in OpenShift.
  storageClassName: hostpath

ingress:
  enabled: false

mongodb:
  auth:
    rootPassword: 'rootpassword'
    replicaSetKey: 'replicasetpassword'
    password: 'password'
  extraEnvVars:
    - name: EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU
      value: '1'
